version: '4.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset 
      analysis/dm_reg_dataset_amy.py
      --test-data-file analysis/test_dm_reg_dataset_amy.py
      --output output/dataset.csv
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv
  generate_dm_measures:
    run: >
      ehrql:v1 generate-measures analysis/dm_reg_measures.py
      --output output/unresolved_dm_measures.csv
    outputs:
      moderately_sensitive:
        dataset: output/unresolved_dm_measures.csv
  visualise_measures:
    run: >
      r:latest analysis/visualise_measures.R --output output/plots/*
    needs: [generate_dm_measures]
    outputs:
      moderately_sensitive:
        plots: output/plots/histogram_unresolved_dm*.png

